AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

MethodLength:
  Max: 30

CyclomaticComplexity:
  Max: 30

ParameterLists:
  Enabled: false

ClassLength:
  Max: 200
