AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
